services:
  application:
    build:
      context: ./Dockerfile
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "5000"
    Volumes:
      - ./Docker:/app
    networks:
      - app-networks

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"
    Volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - application
    networks:
      - app-network

networks:
  app-network:
  driver: bridge
